const ACTION ={
    CHANGE_EXECUTION: 'CHANGE_EXECUTION',
    EDIT_TASK: 'EDIT_TASK',
    DELETE_TASK: 'DELETE_TASK',
    DELETE_ALL_TASKS: 'DELETE_ALL_TASKS',
    CHANGE_FILTER: 'CHANGE_FILTER',
    ADD_TASK: 'ADD_TASK'
}
export default ACTION;